name: build
run-name: build
on: [push]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-rpm:
    runs-on: ubuntu-latest
    container:
      image: docker.io/library/fedora:40
    steps:
    - name: install dependencies
      run: dnf install -y git mock rpm-build rpmdevtools
    - name: checkout
      uses: actions/checkout@v4
    - name: checkout mesa
      run: git clone --depth=1 https://gitlab.freedesktop.org/mesa/mesa.git
    - name: create mesa source tarball
      run: >
        mkdir -p ${HOME}/rpmbuild/SOURCES/ &&
        tar -czf ${HOME}/rpmbuild/SOURCES/mesa.tar.gz mesa
    - name: export version vars
      run: >
        export MESA_VERSION=$(cat ./mesa/VERSION) &&
        export MESA_GIT_SHA=$(GIT_DIR=./mesa git rev-parse --short HEAD)
    - name: build srpm
      run: rpmbuild -bs --define="ver ${MESA_VERSION}" --define="commitsha ${MESA_GIT_SHA}" mesa.spec
    - name: build i386
      run: >
        find /root/rpmbuild/SRPMS/ -name '*.src.rpm' | xargs -n 1
          mock -r fedora-40-i386 --rebuild --resultdir /out/rpm
    - name: build x86_64
      run: >
        find /root/rpmbuild/SRPMS/ -name '*.src.rpm' | xargs -n 1
          mock -r fedora-40-x86_64 --rebuild --resultdir /out/rpm
    - name: save artifacts
      uses: actions/upload-artifact@v4
      with:
        name: rpms
        path: /out/rpm


    # permissions:
    #   contents: read
    #   packages: write
    #   attestations: write
    # steps:
    # - name: ghcr login
    #   uses: docker/login-action@v3
    #   with:
    #     registry: ${{ env.REGISTRY }}
    #     username: ${{ github.actor }}
    #     password: ${{ secrets.GITHUB_TOKEN }}
    # - name: checkout
    #   uses: actions/checkout@v4
    # - name: build
    #   run: >
    #     buildah build
    #     --isolation=chroot
    #     -f Containerfile
    #     --platform=linux/amd64
    #     -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
    #     .
    # - name: push image
    #   run: buildah push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
