name: build
run-name: build
on: [push]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
    steps:
    - name: ghcr login
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: checkout
      uses: actions/checkout@v4
    - name: build
      run: >
        buildah build
        --isolation=chroot
        -f Containerfile
        --platform=linux/amd64
        -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
        .
    - name: push image
      run: buildah push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
